server:
  port: 7001

spring:
  application:
    name: open-platform-alg

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://op:123456@localhost:7000/eureka
  instance:
    prefer-ip-address: true